"""empty message

Revision ID: 2029f169a2ea
Revises: 
Create Date: 2020-04-17 14:11:52.462353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2029f169a2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=25), nullable=True),
    sa.Column('surname', sa.String(length=25), nullable=True),
    sa.Column('chatname', sa.String(length=20), nullable=True),
    sa.Column('githubname', sa.String(length=30), nullable=True),
    sa.Column('idnumber', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('recruits')
    # ### end Alembic commands ###
